services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev

  keycloak-open-webui:
    container_name: keycloak-open-webui
    image: ghcr.io/notyusheng/open-webui_secure
    ports: 
      - "8081:8080"
    environment:
      - OAUTH_CLIENT_ID=open-webui
      - OAUTH_CLIENT_SECRET=VwzAlIWuuafwuEcEB3svrMEZbTWgldWj
      - OPENID_PROVIDER_URL=http://192.168.1.111:8079/realms/myrealm/.well-known/openid-configuration # Replace with your IP
      - OAUTH_PROVIDER_NAME=Keycloak
      - ENABLE_OAUTH_SIGNUP=true
