services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - "9080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev
    # TODO: Missing volumes for persistent data

  keycloak-open-webui:
    container_name: keycloak-open-webui
    image: ghcr.io/notyusheng/open-webui_secure
    ports:
      - "9081:8080"
    environment:
      - OAUTH_CLIENT_ID=open-webui
      - OAUTH_CLIENT_SECRET=VhA8hNVLGg2UVvw9uYREn1RskuZ0fKOb
      - OPENID_PROVIDER_URL=http://192.168.1.111:9080/realms/master/.well-known/openid-configuration
      - OAUTH_PROVIDER_NAME=Keycloak
      - ENABLE_OAUTH_SIGNUP=true

volumes:
  keycloak_data:
