services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]  # dev mode for simplicity, change for production
    ports:
      - "8079:8080"  # Keycloak UI exposed on localhost:8080
    networks:
      - auth-network

  keycloak-db:
    container_name: keycloak-db
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - auth-network

  openwebui:
    container_name: openwebui
    image: ghcr.io/open-webui/open-webui:git-e6ff416-cuda
    environment:
      - WEBUI_AUTH=false  # Disable native auth
    networks:
      - auth-network

  keycloak-oauth2-proxy:
    container_name: keycloak-oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    environment:
      - OAUTH2_PROXY_PROVIDER=keycloak
      - OAUTH2_PROXY_CLIENT_ID=openwebui
      - OAUTH2_PROXY_CLIENT_SECRET=replace_with_your_client_secret
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/realms/myrealm
      - OAUTH2_PROXY_UPSTREAMS=http://openwebui:8080/
      - OAUTH2_PROXY_COOKIE_SECRET=replace_with_random_32_byte_secret
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    ports:
      - "4180:4180"  # You'll access OpenWebUI at http://localhost:4180
    networks:
      - auth-network

volumes:
  keycloak-db-data:

networks:
  auth-network:
