services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

  keycloak-open-webui:
    container_name: keycloak-open-webui
    image: ghcr.io/notyusheng/open-webui_secure
    ports:
      - "${OPENWEBUI_PORT}:8080"
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      # Dynamically construct the OpenID Provider URL using the provided settings:
      # PROTOCOL, HOST_ADDRESS, PORT, and REALM.
      # Note: You may choose to remove HOST_ADDRESS:PORT for Keycloak domain instead
      OPENID_PROVIDER_URL: ${PROTOCOL}://${HOST_ADDRESS}:${PORT}/realms/${REALM}/.well-known/openid-configuration
      OAUTH_PROVIDER_NAME: ${OAUTH_PROVIDER_NAME}
      ENABLE_OAUTH_SIGNUP: ${ENABLE_OAUTH_SIGNUP}

volumes:
  keycloak_data:
